---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: requirements.yml

driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: zabbix-server-${MOLECULE_CONTAINER:-mysql-centos}
    image: ${MOLECULE_IMAGE:-milcom/centos7-systemd}
    privileged: True
    command: /sbin/init
    groups:
      - ${MOLECULE_GROUP:-mysql}

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      mysql:
        zabbix_server_database: mysql
        zabbix_server_database_long: mysql
        zabbix_server_dbport: 3306
      postgresql:
        zabbix_server_database: pgsql
        zabbix_server_database_long: postgresql

scenario:
  name: default
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge

verifier:
  name: testinfra
  lint:
    name: flake8
